//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishingSpots.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FishingSpots.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FISHING SPOTS.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to high.
        /// </summary>
        public static string TideHigh {
            get {
                return ResourceManager.GetString("TideHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incoming.
        /// </summary>
        public static string TideIncoming {
            get {
                return ResourceManager.GetString("TideIncoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to low.
        /// </summary>
        public static string TideLow {
            get {
                return ResourceManager.GetString("TideLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non-tidal.
        /// </summary>
        public static string TideNontidal {
            get {
                return ResourceManager.GetString("TideNontidal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to outgoing.
        /// </summary>
        public static string TideOutgoing {
            get {
                return ResourceManager.GetString("TideOutgoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to slack (high).
        /// </summary>
        public static string TideSlackHigh {
            get {
                return ResourceManager.GetString("TideSlackHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to slack (low).
        /// </summary>
        public static string TideSlackLow {
            get {
                return ResourceManager.GetString("TideSlackLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear.
        /// </summary>
        public static string WeatherClear {
            get {
                return ResourceManager.GetString("WeatherClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heavy rain.
        /// </summary>
        public static string WeatherHeavyRain {
            get {
                return ResourceManager.GetString("WeatherHeavyRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to light rain.
        /// </summary>
        public static string WeatherLightRain {
            get {
                return ResourceManager.GetString("WeatherLightRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overcast.
        /// </summary>
        public static string WeatherOvercast {
            get {
                return ResourceManager.GetString("WeatherOvercast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to partly cloudy.
        /// </summary>
        public static string WeatherPartlyCloudy {
            get {
                return ResourceManager.GetString("WeatherPartlyCloudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rain.
        /// </summary>
        public static string WeatherRain {
            get {
                return ResourceManager.GetString("WeatherRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to snow.
        /// </summary>
        public static string WeatherSnow {
            get {
                return ResourceManager.GetString("WeatherSnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sunny.
        /// </summary>
        public static string WeatherSunny {
            get {
                return ResourceManager.GetString("WeatherSunny", resourceCulture);
            }
        }
    }
}
